# ----------------------------------------
# Overrides for kube-prometheus-stack Helm chart
# Target: Local development using k3d
# Purpose: Reduce resource usage, simplify setup
# ----------------------------------------

# --- Global Settings ---
# Dev Note: We don't need Alertmanager for this local setup.
alertmanager:
  enabled: false

grafana:
  service:
    type: NodePort

    # Dev Note: NodePorts must be in the range 30000-32767.
    nodePort: 30900

  # WARNING: it is a Hardcoded admin password for local use only. Never use in production.
  adminPassword: "admin"

prometheus:
  prometheusSpec:
    # Dev Note: Reduce resource usage for local testing.
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

    retention: 5d
    # Dev Note: Disable long-term storage for local testing.
    remoteWrite: []

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
