# --------------------------------------
# Dockerfile for Jenkins with Docker and kubectl
# Purpose: Set up Jenkins with Docker and kubectl for CI/CD
# Target: Local development using k3d
# --------------------------------------


FROM jenkins/jenkins:lts-jdk11

USER root

RUN apt-get update && apt-get install -y git curl sudo

RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh get-docker.sh

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
RUN rm kubectl

# Dev Note: removed Trivy security scanner feature, due to buggy behavior with jenkins.
# Dev Note: Add the 'jenkins' user to the 'docker' group so it can use the Docker socket without sudo
RUN usermod -aG docker jenkins

# Dev Note: Switches back to the jenkins user for normal operation.
USER jenkins
